openapi: 3.0.3
info:
  contact:
    name: Support
    url: https://github.com/Sage-Bionetworks/sage-monorepo
  license:
    name: Apache 2.0
    url: https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/LICENSE.txt
  title: Model-AD API Next
  version: 1.0.0
  x-logo:
    url: https://dev.modeladexplorer.org/opengraph/opengraph.png
    altText: Model-AD Explorer
servers:
  - url: http://localhost/v1
tags:
  - description: Operations about the data version.
    name: Data Version
  - description: Operations about models.
    name: Model
  - description: Operations about Model Overview.
    name: Model Overview
  - description: Operations about Comparison Tool UI configuration.
    name: Comparison Tool Config
  - description: Operations about Disease Correlation results.
    name: Disease Correlation
paths:
  /data-version:
    get:
      description: Get data version
      operationId: getDataVersion
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataVersion'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get data version
      tags:
        - Data Version
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Data Version
    x-audience:
      - public
  /models/search:
    get:
      description: Search for a particular model
      operationId: searchModels
      parameters:
        - description: Search query
          explode: true
          in: query
          name: q
          required: true
          schema:
            type: string
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SearchResult'
                type: array
          description: Successfully retrieved search results
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Search Models
      tags:
        - Model
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Model
  /models/{name}:
    get:
      description: Retrieve detailed information for a specific model by its name
      operationId: getModelByName
      parameters:
        - description: Name of the model to retrieve
          explode: false
          in: path
          name: name
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: Successfully retrieved model details
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get details for a specific model
      tags:
        - Model
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Model
  /comparison-tool-config:
    get:
      description: Retrieve the Comparison Tool configuration schema for the Model-AD
        application
      operationId: getComparisonToolConfig
      parameters:
        - description: Name of the page to retrieve the Comparison Tool configuration
            for
          explode: true
          in: query
          name: page
          required: true
          schema:
            $ref: '#/components/schemas/ComparisonToolPage'
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ComparisonToolConfig'
                type: array
          description: Successfully retrieved Comparison Tool configuration
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get Comparison Tool configuration
      tags:
        - Comparison Tool Config
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Comparison Tool Config
  /comparison-tools/model-overview:
    get:
      description: Returns a list of model overview objects for use in comparison
        tools.
      operationId: getModelOverviews
      parameters:
        - description: A list of items to filter the data by.
          explode: true
          in: query
          name: item
          required: false
          schema:
            items:
              type: string
            type: array
          style: form
        - description: The type of filter to apply to the items. Possible values are
            'include' or 'exclude'.
          explode: true
          in: query
          name: itemFilterType
          required: false
          schema:
            $ref: '#/components/schemas/ItemFilterTypeQuery'
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ModelOverview'
                type: array
          description: A list of model overview objects
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get model overview for comparison tools
      tags:
        - Model Overview
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Model Overview
  /comparison-tools/disease-correlation:
    get:
      description: Returns a list of disease correlation objects for use in comparison
        tools.
      operationId: getDiseaseCorrelations
      parameters:
        - description: "An ordered list of categories used to filter the data, where\
            \ the first value is the category and the second is the subcategory. Pass\
            \ each value by repeating the 'category' query parameter, e.g. ?category=category1&category=subcategoryA."
          explode: true
          in: query
          name: category
          required: true
          schema:
            items:
              type: string
            type: array
          style: form
        - description: A list of items to filter the data by.
          explode: true
          in: query
          name: item
          required: false
          schema:
            items:
              type: string
            type: array
          style: form
        - description: The type of filter to apply to the items. Possible values are
            'include' or 'exclude'.
          explode: true
          in: query
          name: itemFilterType
          required: false
          schema:
            $ref: '#/components/schemas/ItemFilterTypeQuery'
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DiseaseCorrelation'
                type: array
          description: A list of disease correlation objects
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get disease correlation comparison data
      tags:
        - Disease Correlation
      x-accepts:
        - application/json
        - application/problem+json
      x-tags:
        - tag: Disease Correlation
components:
  parameters:
    itemQuery:
      description: A list of items to filter the data by.
      explode: true
      in: query
      name: item
      required: false
      schema:
        items:
          type: string
        type: array
      style: form
    itemFilterTypeQuery:
      description: The type of filter to apply to the items. Possible values are 'include'
        or 'exclude'.
      explode: true
      in: query
      name: itemFilterType
      required: false
      schema:
        $ref: '#/components/schemas/ItemFilterTypeQuery'
      style: form
    categoryQuery:
      description: "An ordered list of categories used to filter the data, where the\
        \ first value is the category and the second is the subcategory. Pass each\
        \ value by repeating the 'category' query parameter, e.g. ?category=category1&category=subcategoryA."
      explode: true
      in: query
      name: category
      required: true
      schema:
        items:
          type: string
        type: array
      style: form
  responses:
    BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: Invalid request
    NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: The specified resource was not found
    InternalServerError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: The request cannot be fulfilled due to an unexpected server error
  schemas:
    DataVersion:
      description: Synapse data version
      example:
        data_file: data_file
        data_version: data_version
      properties:
        data_file:
          type: string
        data_version:
          type: string
      required:
        - data_file
        - data_version
      type: object
    BasicError:
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          description: A human readable documentation for the problem type
          type: string
        status:
          description: The HTTP status code
          type: integer
        detail:
          description: A human readable explanation specific to this occurrence of
            the problem
          type: string
        type:
          description: An absolute URI that identifies the problem type
          type: string
        instance:
          description: An absolute URI that identifies the specific occurrence of
            the problem
          type: string
      required:
        - status
        - title
      type: object
    SearchResult:
      description: Search result
      example:
        id: id
        match_value: match_value
        match_field: match_field
      properties:
        id:
          description: ID of result
          type: string
        match_field:
          description: Field that matched the query
          type: string
        match_value:
          description: Value that matched the query
          type: string
      required:
        - id
        - match_field
        - match_value
      type: object
    GeneticInfo:
      description: Genetic information about a model
      example:
        modified_gene: modified_gene
        ensembl_gene_id: ensembl_gene_id
        allele: allele
        mgi_allele_id: 6.027456183070403
        allele_type: allele_type
      properties:
        modified_gene:
          description: Name of the modified gene
          type: string
        ensembl_gene_id:
          description: Ensembl gene ID
          type: string
        allele:
          description: Allele symbol
          type: string
        allele_type:
          description: Type of allele
          type: string
        mgi_allele_id:
          description: MGI allele ID
          type: number
      required:
        - allele
        - allele_type
        - ensembl_gene_id
        - mgi_allele_id
        - modified_gene
      type: object
    Sex:
      description: Sex
      enum:
        - Female
        - Male
      type: string
    IndividualData:
      description: Data for an individual
      example:
        sex: Female
        value: 5.962133916683182
        genotype: genotype
        individual_id: individual_id
      properties:
        genotype:
          description: Genotype of the individual
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        individual_id:
          description: Unique identifier for the individual
          type: string
        value:
          description: Value for the individual
          type: number
      required:
        - genotype
        - individual_id
        - sex
        - value
      type: object
    ModelData:
      description: Data associated with a model
      example:
        evidence_type: evidence_type
        data:
          - sex: Female
            value: 5.962133916683182
            genotype: genotype
            individual_id: individual_id
          - sex: Female
            value: 5.962133916683182
            genotype: genotype
            individual_id: individual_id
        name: name
        tissue: tissue
        units: units
        y_axis_max: 1.4658129805029452
        age: age
      properties:
        name:
          description: Name of the model
          type: string
        evidence_type:
          description: Type of evidence
          type: string
        tissue:
          description: Tissue collected
          type: string
        age:
          description: Age at collection
          type: string
        units:
          description: Units of measurement
          type: string
        y_axis_max:
          description: Maximum value for y-axis in visualizations
          type: number
        data:
          description: Values for each individual
          items:
            $ref: '#/components/schemas/IndividualData'
          type: array
      required:
        - age
        - data
        - evidence_type
        - name
        - tissue
        - units
        - y_axis_max
      type: object
    Model:
      description: Model details
      example:
        genetic_info:
          - modified_gene: modified_gene
            ensembl_gene_id: ensembl_gene_id
            allele: allele
            mgi_allele_id: 6.027456183070403
            allele_type: allele_type
          - modified_gene: modified_gene
            ensembl_gene_id: ensembl_gene_id
            allele: allele
            mgi_allele_id: 6.027456183070403
            allele_type: allele_type
        aliases:
          - aliases
          - aliases
        pathology:
          - evidence_type: evidence_type
            data:
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
            name: name
            tissue: tissue
            units: units
            y_axis_max: 1.4658129805029452
            age: age
          - evidence_type: evidence_type
            data:
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
            name: name
            tissue: tissue
            units: units
            y_axis_max: 1.4658129805029452
            age: age
        contributing_group: contributing_group
        biomarkers:
          - evidence_type: evidence_type
            data:
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
            name: name
            tissue: tissue
            units: units
            y_axis_max: 1.4658129805029452
            age: age
          - evidence_type: evidence_type
            data:
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
              - sex: Female
                value: 5.962133916683182
                genotype: genotype
                individual_id: individual_id
            name: name
            tissue: tissue
            units: units
            y_axis_max: 1.4658129805029452
            age: age
        gene_expression: gene_expression
        disease_correlation: disease_correlation
        matched_controls:
          - matched_controls
          - matched_controls
        model_type: model_type
        jax_id: 0.8008281904610115
        rrid: rrid
        genotype: genotype
        spatial_transcriptomics: spatial_transcriptomics
        alzforum_id: alzforum_id
        study_synid: study_synid
        name: name
      properties:
        name:
          description: Name of the model
          type: string
        matched_controls:
          description: List of matched controls
          items:
            type: string
          type: array
        model_type:
          description: Type of the model
          type: string
        contributing_group:
          description: Group contributing the model
          type: string
        study_synid:
          description: Synapse ID of the study
          type: string
        rrid:
          description: RRID of the model
          type: string
        jax_id:
          description: JAX ID of the model
          type: number
        alzforum_id:
          description: AlzForum ID of the model
          type: string
        genotype:
          description: Genotype of the model
          type: string
        aliases:
          description: List of aliases for the model
          items:
            type: string
          type: array
        gene_expression:
          description: Link to gene expression comparison tool data
          nullable: true
          type: string
        disease_correlation:
          description: Link to disease correlation comparison tool data
          nullable: true
          type: string
        spatial_transcriptomics:
          description: Deprecated field for link to spatial transcriptomics data
          nullable: true
          type: string
        genetic_info:
          description: Genetic information related to the Model
          items:
            $ref: '#/components/schemas/GeneticInfo'
          type: array
        biomarkers:
          description: List of biomarker data associated with the model
          items:
            $ref: '#/components/schemas/ModelData'
          type: array
        pathology:
          description: List of pathology data associated with the model
          items:
            $ref: '#/components/schemas/ModelData'
          type: array
      required:
        - aliases
        - alzforum_id
        - biomarkers
        - contributing_group
        - disease_correlation
        - gene_expression
        - genetic_info
        - genotype
        - jax_id
        - matched_controls
        - model_type
        - name
        - pathology
        - rrid
        - spatial_transcriptomics
        - study_synid
      type: object
    ComparisonToolPage:
      description: The type of comparison tool page
      enum:
        - Model Overview
        - Gene Expression
        - Disease Correlation
      example: Gene Expression
      type: string
    ComparisonToolConfigColumn:
      example:
        name: name
        tooltip: tooltip
        is_hidden: true
        link_url: link_url
        sort_tooltip: sort_tooltip
        is_exported: true
        type: text
        data_key: data_key
        link_text: link_text
      properties:
        name:
          description: The display name of the column.
          type: string
        type:
          description: "The data type of the column. Must be 'text', 'heat_map', 'link_internal',\
            \ 'link_external', or 'primary', where 'primary' is the primary key column\
            \ that uniquely identifies each record in the table."
          enum:
            - text
            - heat_map
            - link_internal
            - link_external
            - primary
          type: string
        data_key:
          description: The key used to retrieve data for this column from the data
            source.
          type: string
        tooltip:
          description: Tooltip text for the column.
          type: string
        sort_tooltip:
          description: Tooltip text for the column's sort functionality.
          type: string
        link_text:
          description: The default text for a link in this column.
          type: string
        link_url:
          description: The default URL for this column.
          type: string
        is_exported:
          description: Indicates whether the column is included in data exports.
          type: boolean
        is_hidden:
          description: Indicates whether the column is shown in the comparison table
            UI.
          type: boolean
      required:
        - data_key
        - is_exported
        - is_hidden
        - type
      type: object
    ComparisonToolConfigFilter:
      description: Comparison Tool Config Filter
      example:
        values:
          - Apoptosis
          - Apoptosis
        name: Biological Domain
        short_name: Biodomain
        data_key: model_type
      properties:
        name:
          description: Name of the filter group
          example: Biological Domain
          type: string
        data_key:
          description: Field to filter on
          example: model_type
          type: string
        short_name:
          description: Short name of the filter group
          example: Biodomain
          type: string
        values:
          description: List of filter values
          items:
            example: Apoptosis
            type: string
          type: array
      required:
        - data_key
        - name
        - values
      type: object
    ComparisonToolConfig:
      example:
        columns:
          - name: name
            tooltip: tooltip
            is_hidden: true
            link_url: link_url
            sort_tooltip: sort_tooltip
            is_exported: true
            type: text
            data_key: data_key
            link_text: link_text
          - name: name
            tooltip: tooltip
            is_hidden: true
            link_url: link_url
            sort_tooltip: sort_tooltip
            is_exported: true
            type: text
            data_key: data_key
            link_text: link_text
        page: Gene Expression
        dropdowns:
          - 'RNA - DIFFERENTIAL EXPRESSION, Tissue - Hippocampus, Sex - Females & Males'
          - 'RNA - DIFFERENTIAL EXPRESSION, Tissue - Hippocampus, Sex - Females & Males'
        filters:
          - values:
              - Apoptosis
              - Apoptosis
            name: Biological Domain
            short_name: Biodomain
            data_key: model_type
          - values:
              - Apoptosis
              - Apoptosis
            name: Biological Domain
            short_name: Biodomain
            data_key: model_type
        row_count: row_count
      properties:
        page:
          $ref: '#/components/schemas/ComparisonToolPage'
        dropdowns:
          description: List of dropdown options
          items:
            example: "RNA - DIFFERENTIAL EXPRESSION, Tissue - Hippocampus, Sex - Females\
              \ & Males"
            type: string
          type: array
        row_count:
          description: Relative description of the total number of rows in the data
          type: string
        columns:
          description: List of column definitions
          items:
            $ref: '#/components/schemas/ComparisonToolConfigColumn'
          type: array
        filters:
          description: List of filter configurations
          items:
            $ref: '#/components/schemas/ComparisonToolConfigFilter'
          type: array
      required:
        - columns
        - dropdowns
        - filters
        - page
        - row_count
      type: object
    ItemFilterTypeQuery:
      default: include
      description: |
        - include: Include only the specified items.
        - exclude: Exclude the specified items.
      enum:
        - include
        - exclude
      type: string
    ModelOverviewLink:
      description: Model Overview Link
      example:
        link_url: link_url
        link_text: link_text
      properties:
        link_text:
          description: Link text
          type: string
        link_url:
          description: URL for the related resource
          type: string
      type: object
    ModelOverview:
      description: Model Overview object for comparison tools
      example:
        pathology:
          link_url: link_url
          link_text: link_text
        biomarkers:
          link_url: link_url
          link_text: link_text
        gene_expression:
          link_url: link_url
          link_text: link_text
        disease_correlation:
          link_url: link_url
          link_text: link_text
        center:
          link_url: link_url
          link_text: link_text
        model_type: model_type
        matched_controls:
          - matched_controls
          - matched_controls
        modified_genes:
          - modified_genes
          - modified_genes
        available_data:
          - Gene Expression
          - Gene Expression
        name: name
        jax_strain:
          link_url: link_url
          link_text: link_text
        _id: _id
        study_data:
          link_url: link_url
          link_text: link_text
      properties:
        _id:
          description: Unique identifier for the model overview object
          type: string
        name:
          description: Model name
          type: string
        model_type:
          description: 'Model type (e.g., Late Onset AD, Familial AD)'
          type: string
        matched_controls:
          description: List of matched control models
          items:
            type: string
          type: array
        gene_expression:
          $ref: '#/components/schemas/ModelOverviewLink'
        disease_correlation:
          $ref: '#/components/schemas/ModelOverviewLink'
        biomarkers:
          $ref: '#/components/schemas/ModelOverviewLink'
        pathology:
          $ref: '#/components/schemas/ModelOverviewLink'
        study_data:
          $ref: '#/components/schemas/ModelOverviewLink'
        jax_strain:
          $ref: '#/components/schemas/ModelOverviewLink'
        center:
          $ref: '#/components/schemas/ModelOverviewLink'
        modified_genes:
          description: List of modified genes in the model
          items:
            type: string
          type: array
        available_data:
          items:
            enum:
              - Gene Expression
              - Pathology
              - Biomarkers
              - Disease Correlation
            type: string
          type: array
      required:
        - _id
        - available_data
        - center
        - jax_strain
        - matched_controls
        - model_type
        - modified_genes
        - name
        - study_data
      type: object
    CorrelationResult:
      description: Correlation result
      example:
        adj_p_val: 6.027456183070403
        correlation: 0.8008281904610115
      properties:
        correlation:
          description: Correlation value
          type: number
        adj_p_val:
          description: Adjusted p-value
          type: number
      required:
        - adj_p_val
        - correlation
      type: object
    DiseaseCorrelation:
      description: Disease Correlation
      example:
        cluster: cluster
        DLPFC:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        sex: Female
        CBE:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        STG:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        model_type: model_type
        TCX:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        modified_genes:
          - modified_genes
          - modified_genes
        FP:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        IFG:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        matched_control: matched_control
        PHG:
          adj_p_val: 6.027456183070403
          correlation: 0.8008281904610115
        name: name
        _id: _id
        age: age
      properties:
        _id:
          description: Unique identifier for the disease correlation object
          type: string
        name:
          description: Model name
          type: string
        matched_control:
          description: Matched control for the model
          type: string
        model_type:
          description: Type of model
          type: string
        modified_genes:
          description: List of modified genes
          items:
            type: string
          type: array
        cluster:
          description: Cluster information
          type: string
        age:
          description: Age of the model
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        IFG:
          $ref: '#/components/schemas/CorrelationResult'
        PHG:
          $ref: '#/components/schemas/CorrelationResult'
        TCX:
          $ref: '#/components/schemas/CorrelationResult'
        CBE:
          $ref: '#/components/schemas/CorrelationResult'
        DLPFC:
          $ref: '#/components/schemas/CorrelationResult'
        FP:
          $ref: '#/components/schemas/CorrelationResult'
        STG:
          $ref: '#/components/schemas/CorrelationResult'
      required:
        - _id
        - age
        - cluster
        - matched_control
        - model_type
        - modified_genes
        - name
        - sex
      type: object
