openapi: 3.0.3
info:
  contact:
    name: Support
    url: https://github.com/Sage-Bionetworks/sage-monorepo
  license:
    name: Apache 2.0
    url: https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/LICENSE.txt
  title: OpenChallenges Challenge REST API
  version: 1.0.0
  x-logo:
    url: https://dev.openchallenges.io/img/unsafe/logo/OpenChallenges-logo.png
servers:
- url: http://localhost/v1
tags:
- description: Operations about challenges.
  name: Challenge
- description: Operations about challenge analytics.
  name: ChallengeAnalytics
- description: Operations about challenge platforms.
  name: ChallengePlatform
- description: Operations about EDAM concepts.
  name: EdamConcept
paths:
  /challenges:
    get:
      description: List challenges
      operationId: listChallenges
      parameters:
      - description: The search query used to find challenges.
        explode: true
        in: query
        name: challengeSearchQuery
        required: false
        schema:
          $ref: '#/components/schemas/ChallengeSearchQuery'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengesPage'
          description: Success
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: Invalid request
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: List challenges
      tags:
      - Challenge
      x-accepts: application/json
      x-tags:
      - tag: Challenge
  /challenges/{challengeId}:
    get:
      description: Returns the challenge specified
      operationId: getChallenge
      parameters:
      - description: The unique identifier of the challenge.
        explode: false
        in: path
        name: challengeId
        required: true
        schema:
          $ref: '#/components/schemas/ChallengeId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenge'
          description: A challenge
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The specified resource was not found
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get a challenge
      tags:
      - Challenge
      x-accepts: application/json
      x-tags:
      - tag: Challenge
  /challenges/{challengeId}/contributions:
    get:
      description: List challenge contributions
      operationId: listChallengeContributions
      parameters:
      - description: The unique identifier of the challenge.
        explode: false
        in: path
        name: challengeId
        required: true
        schema:
          $ref: '#/components/schemas/ChallengeId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengeContributionsPage'
          description: Success
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: Invalid request
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: List challenge contributions
      tags:
      - ChallengeContribution
      x-accepts: application/json
      x-tags:
      - tag: ChallengeContribution
  /challengeAnalytics/challengesPerYear:
    get:
      description: Returns the number of challenges tracked per year
      operationId: getChallengesPerYear
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengesPerYear'
          description: An object
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get the number of challenges tracked per year
      tags:
      - ChallengeAnalytics
      x-accepts: application/json
      x-tags:
      - tag: ChallengeAnalytics
  /challengePlatforms:
    get:
      description: List challenge platforms
      operationId: listChallengePlatforms
      parameters:
      - description: The search query used to find challenge platforms.
        explode: true
        in: query
        name: challengePlatformSearchQuery
        required: false
        schema:
          $ref: '#/components/schemas/ChallengePlatformSearchQuery'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengePlatformsPage'
          description: Success
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: Invalid request
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: List challenge platforms
      tags:
      - ChallengePlatform
      x-accepts: application/json
      x-tags:
      - tag: ChallengePlatform
  /challengePlatforms/{challengePlatformName}:
    get:
      description: Returns the challenge platform specified
      operationId: getChallengePlatform
      parameters:
      - description: The unique identifier of the challenge platform.
        explode: false
        in: path
        name: challengePlatformName
        required: true
        schema:
          $ref: '#/components/schemas/ChallengePlatformName'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengePlatform'
          description: Success
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The specified resource was not found
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get a challenge platform
      tags:
      - ChallengePlatform
      x-accepts: application/json
      x-tags:
      - tag: ChallengePlatform
  /edamConcepts:
    get:
      description: List EDAM concepts
      operationId: listEdamConcepts
      parameters:
      - description: The search query used to find EDAM concepts.
        explode: true
        in: query
        name: edamConceptSearchQuery
        required: false
        schema:
          $ref: '#/components/schemas/EdamConceptSearchQuery'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdamConceptsPage'
          description: Success
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: Invalid request
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BasicError'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: List EDAM concepts
      tags:
      - EdamConcept
      x-accepts: application/json
      x-tags:
      - tag: EdamConcept
components:
  parameters:
    challengeSearchQuery:
      description: The search query used to find challenges.
      explode: true
      in: query
      name: challengeSearchQuery
      required: false
      schema:
        $ref: '#/components/schemas/ChallengeSearchQuery'
      style: form
    challengeId:
      description: The unique identifier of the challenge.
      explode: false
      in: path
      name: challengeId
      required: true
      schema:
        $ref: '#/components/schemas/ChallengeId'
      style: simple
    challengePlatformSearchQuery:
      description: The search query used to find challenge platforms.
      explode: true
      in: query
      name: challengePlatformSearchQuery
      required: false
      schema:
        $ref: '#/components/schemas/ChallengePlatformSearchQuery'
      style: form
    challengePlatformName:
      description: The unique identifier of the challenge platform.
      explode: false
      in: path
      name: challengePlatformName
      required: true
      schema:
        $ref: '#/components/schemas/ChallengePlatformName'
      style: simple
    edamConceptSearchQuery:
      description: The search query used to find EDAM concepts.
      explode: true
      in: query
      name: edamConceptSearchQuery
      required: false
      schema:
        $ref: '#/components/schemas/EdamConceptSearchQuery'
      style: form
  responses:
    BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: Invalid request
    InternalServerError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: The request cannot be fulfilled due to an unexpected server error
    NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BasicError'
      description: The specified resource was not found
  schemas:
    ChallengeSort:
      default: relevance
      description: What to sort results by.
      enum:
      - created
      - random
      - relevance
      - starred
      - start_date
      - end_date
      type: string
    ChallengeDirection:
      description: The direction to sort the results by.
      enum:
      - asc
      - desc
      nullable: true
      type: string
    ChallengeIncentive:
      description: The incentive type of the challenge.
      enum:
      - monetary
      - publication
      - speaking_engagement
      - other
      example: publication
      type: string
    ChallengePlatformSlug:
      description: The slug of the challenge platform.
      example: example-challenge-platform
      maxLength: 30
      minLength: 3
      pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      type: string
    OrganizationId:
      description: The unique identifier of an organization
      example: 1
      format: int64
      type: integer
    ChallengeStatus:
      description: The status of the challenge.
      enum:
      - upcoming
      - active
      - completed
      example: active
      type: string
    ChallengeSubmissionType:
      description: The submission type of the challenge.
      enum:
      - container_image
      - prediction_file
      - notebook
      - mlcube
      - other
      example: container_image
      type: string
    EdamConceptId:
      description: The unique identifier of the EDAM concept.
      example: 1
      format: int64
      type: integer
    ChallengeCategory:
      description: The category of the challenge.
      enum:
      - featured
      - benchmark
      - hackathon
      - starting_soon
      - ending_soon
      - recently_started
      - recently_ended
      example: featured
      type: string
    ChallengeSearchQuery:
      description: A challenge search query.
      properties:
        pageNumber:
          default: 0
          description: The page number.
          format: int32
          minimum: 0
          type: integer
        pageSize:
          default: 100
          description: The number of items in a single page.
          format: int32
          minimum: 1
          type: integer
        sort:
          $ref: '#/components/schemas/ChallengeSort'
        sortSeed:
          description: The seed that initializes the random sorter.
          format: int32
          maximum: 2147483647
          minimum: 0
          nullable: true
          type: integer
        direction:
          $ref: '#/components/schemas/ChallengeDirection'
        incentives:
          description: An array of challenge incentive types used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengeIncentive'
          type: array
        minStartDate:
          description: Keep the challenges that start at this date or later.
          example: 2017-07-21
          format: date
          nullable: true
          type: string
        maxStartDate:
          description: Keep the challenges that start at this date or sooner.
          example: 2017-07-21
          format: date
          nullable: true
          type: string
        platforms:
          description: An array of challenge platform ids used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengePlatformSlug'
          type: array
        organizations:
          description: An array of organization ids used to filter the results.
          items:
            $ref: '#/components/schemas/OrganizationId'
          type: array
        status:
          description: An array of challenge status used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengeStatus'
          type: array
        submissionTypes:
          description: An array of challenge submission types used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengeSubmissionType'
          type: array
        inputDataTypes:
          description: An array of EDAM concept ID used to filter the results.
          items:
            $ref: '#/components/schemas/EdamConceptId'
          type: array
        operations:
          description: An array of EDAM concept ID used to filter the results.
          items:
            $ref: '#/components/schemas/EdamConceptId'
          type: array
        categories:
          description: The array of challenge categories used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengeCategory'
          type: array
        searchTerms:
          description: A string of search terms used to filter the results.
          example: dream challenge
          type: string
      type: object
    PageMetadata:
      description: The metadata of a page.
      properties:
        number:
          description: The page number.
          example: 99
          format: int32
          type: integer
        size:
          description: The number of items in a single page.
          example: 99
          format: int32
          type: integer
        totalElements:
          description: Total number of elements in the result set.
          example: 99
          format: int64
          type: integer
        totalPages:
          description: Total number of pages in the result set.
          example: 99
          format: int32
          type: integer
        hasNext:
          description: Returns if there is a next page.
          example: true
          type: boolean
        hasPrevious:
          description: Returns if there is a previous page.
          example: true
          type: boolean
      required:
      - hasNext
      - hasPrevious
      - number
      - size
      - totalElements
      - totalPages
      type: object
    ChallengeId:
      description: The unique identifier of the challenge.
      example: 1
      format: int64
      type: integer
    ChallengeSlug:
      description: The unique slug of the challenge.
      example: awesome-challenge
      maxLength: 255
      minLength: 3
      pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      type: string
    ChallengeName:
      description: The name of the challenge.
      maxLength: 255
      minLength: 3
      type: string
    ChallengeHeadline:
      description: The headline of the challenge.
      example: Example challenge headline
      maxLength: 80
      minLength: 0
      nullable: true
      type: string
    ChallengeDescription:
      description: The description of the challenge.
      example: This is an example description of the challenge.
      maxLength: 1000
      minLength: 0
      type: string
    ChallengeDoi:
      description: The DOI of the challenge.
      example: https://doi.org/123/abc
      format: url
      maxLength: 120
      nullable: true
      type: string
    ChallengePlatformId:
      description: The unique identifier of a challenge platform.
      example: 1
      format: int64
      type: integer
    ChallengePlatformName:
      description: The name of the challenge platform.
      maxLength: 30
      minLength: 3
      type: string
    SimpleChallengePlatform:
      description: A simple challenge platform.
      example:
        name: name
        id: 1
        slug: example-challenge-platform
      nullable: true
      properties:
        id:
          description: The unique identifier of a challenge platform.
          example: 1
          format: int64
          type: integer
        slug:
          description: The slug of the challenge platform.
          example: example-challenge-platform
          maxLength: 30
          minLength: 3
          pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          type: string
        name:
          description: The name of the challenge platform.
          maxLength: 30
          minLength: 3
          type: string
      required:
      - id
      - name
      - slug
      type: object
    Url:
      description: A URL to the website or image.
      example: https://openchallenges.io
      format: url
      maxLength: 500
      nullable: true
      type: string
    EdamConcept:
      description: The EDAM concept.
      example:
        classId: http://edamontology.org/data_0850
        preferredLabel: Sequence set
        id: 1
      nullable: true
      properties:
        id:
          description: The unique identifier of the EDAM concept.
          example: 1
          format: int64
          type: integer
        classId:
          example: http://edamontology.org/data_0850
          maxLength: 60
          type: string
        preferredLabel:
          example: Sequence set
          maxLength: 80
          type: string
      required:
      - classId
      - id
      - preferredLabel
      type: object
    ChallengeStartDate:
      description: The start date of the challenge.
      example: 2017-07-21
      format: date
      nullable: true
      type: string
    ChallengeEndDate:
      description: The end date of the challenge.
      example: 2017-07-21
      format: date
      nullable: true
      type: string
    CreatedDateTime:
      description: Datetime when the object was added to the database.
      example: 2022-07-04T22:19:11Z
      format: date-time
      type: string
    UpdatedDateTime:
      description: Datetime when the object was last modified in the database.
      example: 2022-07-04T22:19:11Z
      format: date-time
      type: string
    Challenge:
      description: A challenge
      example:
        avatarUrl: https://openchallenges.io
        endDate: 2017-07-21T00:00:00.000+00:00
        description: This is an example description of the challenge.
        platform:
          name: name
          id: 1
          slug: example-challenge-platform
        starredCount: 100
        createdAt: 2022-07-04T22:19:11Z
        incentives:
        - publication
        - publication
        submissionTypes:
        - container_image
        - container_image
        websiteUrl: https://openchallenges.io
        name: name
        id: 1
        categories:
        - featured
        - featured
        headline: Example challenge headline
        operation:
          classId: http://edamontology.org/data_0850
          preferredLabel: Sequence set
          id: 1
        slug: awesome-challenge
        startDate: 2017-07-21T00:00:00.000+00:00
        doi: https://doi.org/123/abc
        status: active
        inputDataTypes:
        - classId: http://edamontology.org/data_0850
          preferredLabel: Sequence set
          id: 1
        - classId: http://edamontology.org/data_0850
          preferredLabel: Sequence set
          id: 1
        updatedAt: 2022-07-04T22:19:11Z
      properties:
        id:
          description: The unique identifier of the challenge.
          example: 1
          format: int64
          type: integer
        slug:
          description: The unique slug of the challenge.
          example: awesome-challenge
          maxLength: 255
          minLength: 3
          pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          type: string
        name:
          description: The name of the challenge.
          maxLength: 255
          minLength: 3
          type: string
        headline:
          description: The headline of the challenge.
          example: Example challenge headline
          maxLength: 80
          minLength: 0
          nullable: true
          type: string
        description:
          description: The description of the challenge.
          example: This is an example description of the challenge.
          maxLength: 1000
          minLength: 0
          type: string
        doi:
          description: The DOI of the challenge.
          example: https://doi.org/123/abc
          format: url
          maxLength: 120
          nullable: true
          type: string
        status:
          $ref: '#/components/schemas/ChallengeStatus'
        platform:
          $ref: '#/components/schemas/SimpleChallengePlatform'
        websiteUrl:
          description: A URL to the website or image.
          example: https://openchallenges.io
          format: url
          maxLength: 500
          nullable: true
          type: string
        avatarUrl:
          description: A URL to the website or image.
          example: https://openchallenges.io
          format: url
          maxLength: 500
          nullable: true
          type: string
        incentives:
          items:
            $ref: '#/components/schemas/ChallengeIncentive'
          type: array
        submissionTypes:
          items:
            $ref: '#/components/schemas/ChallengeSubmissionType'
          type: array
        inputDataTypes:
          items:
            $ref: '#/components/schemas/EdamConcept'
          type: array
        categories:
          items:
            $ref: '#/components/schemas/ChallengeCategory'
          type: array
        startDate:
          description: The start date of the challenge.
          example: 2017-07-21
          format: date
          nullable: true
          type: string
        endDate:
          description: The end date of the challenge.
          example: 2017-07-21
          format: date
          nullable: true
          type: string
        starredCount:
          default: 0
          description: The number of times the challenge has been starred by users.
          example: 100
          minimum: 0
          type: integer
        operation:
          $ref: '#/components/schemas/EdamConcept'
        createdAt:
          description: Datetime when the object was added to the database.
          example: 2022-07-04T22:19:11Z
          format: date-time
          type: string
        updatedAt:
          description: Datetime when the object was last modified in the database.
          example: 2022-07-04T22:19:11Z
          format: date-time
          type: string
      required:
      - categories
      - createdAt
      - description
      - id
      - incentives
      - name
      - slug
      - starredCount
      - status
      - submissionTypes
      - updatedAt
      type: object
    ChallengesPage:
      allOf:
      - $ref: '#/components/schemas/PageMetadata'
      - $ref: '#/components/schemas/ChallengesPage_allOf'
      description: A page of challenges.
      type: object
      x-java-class-annotations:
      - '@lombok.Builder'
    BasicError:
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          description: A human readable documentation for the problem type
          type: string
        status:
          description: The HTTP status code
          type: integer
        detail:
          description: A human readable explanation specific to this occurrence of
            the problem
          type: string
        type:
          description: An absolute URI that identifies the problem type
          type: string
      required:
      - status
      - title
      type: object
      x-java-class-annotations:
      - '@lombok.AllArgsConstructor'
      - '@lombok.Builder'
    ChallengeContributionRole:
      description: The nature of a challenge contribution.
      enum:
      - challenge_organizer
      - data_contributor
      - sponsor
      example: challenge_organizer
      type: string
    ChallengeContribution:
      description: A challenge contribution.
      properties:
        challengeId:
          description: The unique identifier of the challenge.
          example: 1
          format: int64
          type: integer
        organizationId:
          description: The unique identifier of an organization
          example: 1
          format: int64
          type: integer
        role:
          $ref: '#/components/schemas/ChallengeContributionRole'
      required:
      - challengeId
      - organizationId
      - role
      type: object
    ChallengeContributionsPage:
      allOf:
      - $ref: '#/components/schemas/PageMetadata'
      - $ref: '#/components/schemas/ChallengeContributionsPage_allOf'
      description: A page of challenge challenge contributions.
      type: object
      x-java-class-annotations:
      - '@lombok.Builder'
    ChallengesPerYear:
      description: An object
      example:
        undatedChallengeCount: 0
        challengeCounts:
        - 0
        - 0
        years:
        - years
        - years
      properties:
        years:
          items:
            type: string
          type: array
        challengeCounts:
          items:
            type: integer
          type: array
        undatedChallengeCount:
          default: 0
          example: 0
          minimum: 0
          type: integer
      required:
      - challengeCounts
      - undatedChallengeCount
      - years
      type: object
      x-java-class-annotations:
      - '@lombok.Builder'
    ChallengePlatformSort:
      default: relevance
      description: What to sort results by.
      enum:
      - name
      - relevance
      type: string
    ChallengePlatformDirection:
      description: The direction to sort the results by.
      enum:
      - asc
      - desc
      nullable: true
      type: string
    ChallengePlatformSearchQuery:
      description: A challenge platform search query.
      properties:
        pageNumber:
          default: 0
          description: The page number.
          format: int32
          minimum: 0
          type: integer
        pageSize:
          default: 100
          description: The number of items in a single page.
          format: int32
          minimum: 1
          type: integer
        sort:
          $ref: '#/components/schemas/ChallengePlatformSort'
        direction:
          $ref: '#/components/schemas/ChallengePlatformDirection'
        slugs:
          description: An array of challenge platform slugs used to filter the results.
          items:
            $ref: '#/components/schemas/ChallengePlatformSlug'
          type: array
        searchTerms:
          description: A string of search terms used to filter the results.
          example: synapse
          type: string
      type: object
    ChallengePlatform:
      description: A challenge platform
      example:
        createdAt: 2022-07-04T22:19:11Z
        avatarUrl: https://via.placeholder.com/300.png
        websiteUrl: https://example.com
        name: name
        id: 1
        slug: example-challenge-platform
        updatedAt: 2022-07-04T22:19:11Z
      properties:
        id:
          description: The unique identifier of a challenge platform.
          example: 1
          format: int64
          type: integer
        slug:
          description: The slug of the challenge platform.
          example: example-challenge-platform
          maxLength: 30
          minLength: 3
          pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          type: string
        name:
          description: The name of the challenge platform.
          maxLength: 30
          minLength: 3
          type: string
        avatarUrl:
          example: https://via.placeholder.com/300.png
          format: url
          type: string
        websiteUrl:
          example: https://example.com
          format: url
          type: string
        createdAt:
          example: 2022-07-04T22:19:11Z
          format: date-time
          type: string
        updatedAt:
          example: 2022-07-04T22:19:11Z
          format: date-time
          type: string
      required:
      - avatarUrl
      - createdAt
      - id
      - name
      - slug
      - updatedAt
      - websiteUrl
      type: object
    ChallengePlatformsPage:
      allOf:
      - $ref: '#/components/schemas/PageMetadata'
      - $ref: '#/components/schemas/ChallengePlatformsPage_allOf'
      description: A page of challenge platforms.
      type: object
      x-java-class-annotations:
      - '@lombok.Builder'
    EdamConceptSort:
      default: relevance
      description: What to sort results by.
      enum:
      - preferred_label
      - relevance
      type: string
    EdamConceptDirection:
      description: The direction to sort the results by.
      enum:
      - asc
      - desc
      nullable: true
      type: string
    EdamSection:
      description: The EDAM section (sub-ontology).
      enum:
      - data
      - format
      - identifier
      - operation
      - topic
      example: data
      type: string
    EdamConceptSearchQuery:
      description: An EDAM concept search query.
      properties:
        pageNumber:
          default: 0
          description: The page number.
          format: int32
          minimum: 0
          type: integer
        pageSize:
          default: 100
          description: The number of items in a single page.
          format: int32
          minimum: 1
          type: integer
        sort:
          $ref: '#/components/schemas/EdamConceptSort'
        direction:
          $ref: '#/components/schemas/EdamConceptDirection'
        ids:
          description: An array of EDAM concept ids used to filter the results.
          items:
            $ref: '#/components/schemas/EdamConceptId'
          type: array
        searchTerms:
          description: A string of search terms used to filter the results.
          example: sequence image
          type: string
        sections:
          description: An array of EDAM sections (sub-ontologies) used to filter the
            results.
          items:
            $ref: '#/components/schemas/EdamSection'
          type: array
      type: object
    EdamConceptsPage:
      allOf:
      - $ref: '#/components/schemas/PageMetadata'
      - $ref: '#/components/schemas/EdamConceptsPage_allOf'
      description: A page of EDAM concepts.
      type: object
      x-java-class-annotations:
      - '@lombok.Builder'
    ChallengesPage_allOf:
      properties:
        challenges:
          description: A list of challenges.
          items:
            $ref: '#/components/schemas/Challenge'
          type: array
      required:
      - challenges
      type: object
      example: null
    ChallengeContributionsPage_allOf:
      properties:
        challengeContributions:
          description: A list of challenge contributions.
          items:
            $ref: '#/components/schemas/ChallengeContribution'
          type: array
      required:
      - challengeContributions
      type: object
      example: null
    ChallengePlatformsPage_allOf:
      properties:
        challengePlatforms:
          description: A list of challenge platforms.
          items:
            $ref: '#/components/schemas/ChallengePlatform'
          type: array
      required:
      - challengePlatforms
      type: object
      example: null
    EdamConceptsPage_allOf:
      properties:
        edamConcepts:
          description: A list of EDAM concepts.
          items:
            $ref: '#/components/schemas/EdamConcept'
          type: array
      required:
      - edamConcepts
      type: object
      example: null
